### ISSUE TITLE
How does this deal with complications like Angular material names?

### ISSUE THREAD

**Issue by rafaeldolfe** [navanshu/postcss-variable-compress#37]
It should be considered to add some default ignored prefixes such as `mat-`. If this is added, the README should mention it.

**Comment by navanshu** [comment]
Thanks for the suggestion @rafaeldolfe 
One can pass a function to check for variable one wants to skip transformation of. 
In your case
```typescript
module.exports = {
  plugins: [
    require('cssnano'),
    require('postcss-variable-compress')(
       // Return TRUE to skip that specific variable...
      (name) => name.includes('mat-') 
    )
  ]
}
```
For more info: you can [check here](https://github.com/navanshu/postcss-variable-compress#api)

Do provide me some info about your stack and how you use it. What further optimisation you would like.
I really don't know much how people are using my library and hence struggling to decide on which feature, I should be working on next. 
Do let me know, if you want some other features.
Do star the library. 🙂
