### ISSUE TITLE
Already existing variables get reused

### ISSUE THREAD

**Issue by kinsi55** [navanshu/postcss-variable-compress#43]
I've tried to use this plugin with my Tailwind setup and noticed some colors of things being incorrect, after digging a little bit, I noticed that (I guess) when iterating over variables, it will generate a variable name, but if a later variable then already is named just like one of the generated variables, it wont get a new one and instead stay as-is

This is what the original CSS is:

```
:root {
[...]
  --b3: 231 15% 4%;
[...]
  --a: 31 100% 71%;
}
```

And after the plugin processed it, both of them end up being --a

I reckon a fix could be replacing all `--` with something else, and then running the replacer on that turning them back into `--`, that way you know what was processed already and what wasnt.

**Comment by navanshu** [comment]
@kinsi55 Very Interesting, can you share your postcss.config, might be some other plugin causing this.

**Comment by kinsi55** [comment]
I use Postcss w/ Rollup, this is my setup:

```
postcss({
	extract: "style.css",
	minimize: isProd,
	plugins: [
		require("tailwindcss"),

		isProd && cssnano({
			preset: cssnanoAdvanced
		}),

		isProd && postcssVariableCompress()
	]
}),
```

`isProd` is true for this of course

**Comment by navanshu** [comment]
@kinsi55 There is a option to skip conversion of a variable you can try that, that will ignore that variable. Solving your issue.

Other wise it is impossible for One variable leading to two variables, the later occurrences of such a variable are untraceable

**Comment by kinsi55** [comment]
The problem is that then only shifts the Problem:

![grafik](https://github.com/navanshu/postcss-variable-compress/assets/8348306/552ac4d9-6d98-4536-a071-ff356d0b026a)

As you see, when I tell it to exclude `--b3` it will just use `--a` for the next variable after, so the problem persists

**Comment by navanshu** [comment]
@kinsi55 No, exclude --a,p,s,n, that way no variable will be renamed to --a and your --a will be kept safe
Also I would say if some your variables are already small, you can pass all the small ones to the plugin.

**Comment by kinsi55** [comment]
The thing is these variables are not mine, they are part of Tailwind / DaisyUI. Having to maintain a list of upstream module variables seems kinda.. Wrong.

I think this plugin should work like this:

1. Find all variables, create a Set out of them
2. Create a new Set that tracks all generated variables
3. Have an incrementing number that represents the next replacement variable
4. Iterate over the Set of all existing variables(1), replace them with a new one which does not exist in 1 or 2, add it into 2 (If 3 ends up being an already existing variable, keep incrementing it until it isnt)

**Comment by navanshu** [comment]
Can you elaborate on your solution and how it will handle the scenario when a variable is redeclared in another block, perhaps for dark mode?

Yes, you shouldn't have to deal with upstream variables. By the way, using non-descriptive names is an issue with DaisyUI, whereas Tailwind uses descriptive names.

The purpose of using DaisyUI or Tailwind is to eliminate the need for using CSS variables or custom CSS. You can simply use Tailwind's utility classes or DaisyUI classes, and this will greatly enhance your development experience. This is based on my personal experience, but your mileage may vary.

**Comment by kinsi55** [comment]
I am not modifying or adding any variables myself, any variable that exists does so because they created them.

> Can you elaborate on your solution and how it will handle the scenario when a variable is redeclared in another block, perhaps for dark mode?

You can keep a map of what was mapped to what and just pull from that. As mentioned before, you would probably have to do replacement in 3 steps:

1. Replace the `--` of all variables with something else that is invalid like `||`, this is just so you know which variables have not yet been processed
2. Go through the Set 1 and replace all `||` occurences with the correct, new `--`replacement, this way if you are insering a --0, but the original CSS already contained a --0, that original is now ||0 and will later be replaced with something else, instead of now being indistinguishable
3. replace all remaining `||` with `--` (For the variables that should not get replaced and are skipped in 2)

**Comment by navanshu** [comment]
@kinsi55 I am not sure how postcss algorithm works will it support it or not, more over if the variable names collide then it can also be intended behaviour, also implementing this might double the run time as well.

I personally see this an issue of Daisy UI for not naming the variables.

**Comment by kinsi55** [comment]
I disagree but if that is how you feel, feel free to close the issue. Thanks for the workaround which works for me for now. I might go ahead and try building my own plugin at some point.

**Comment by navanshu** [comment]
If you are willing to try the fix you can fork V3
