### ISSUE TITLE
Feature Request: Variable Consolidation

### ISSUE THREAD

**Issue by jaswrks** [navanshu/postcss-variable-compress#45]
Here's an example output after running `postcss-variable-compress` against a Tailwind compilation. As you can see, due to theme configurations across various extensions for Tailwind that I'm running, I end up with a lot of color variables that are actually the very same color. If `postcss-variable-compress` were able to simply consolidate these into a single variable, discarding the others that are essentially duplicates, it would shave off quite a few bytes more.

Note: `255, 255, 255` appears *many* times here, and in fact I'm only posting a small summary. There are just as many more occurrences of `255, 255, 255` that I'm contending with in the final build. Seems like a waste of precious space. I would imagine that variable consolidation would also speed up rendering time.

```
  --1d: 255, 255, 255;
  --9: 240, 240, 240;
  --b: 128, 175, 249;
  --d: 255, 255, 255;
  --f: 255, 255, 255;
  --h: 255, 255, 255;
  --j: 176, 176, 176;
  --l: 176, 176, 176;
  --n: 176, 176, 176;
  --p: 31, 31, 31;
  --r: 255, 255, 255;
  --t: 240 240 240;
  --v: 255, 255, 255;
  --x: 240 240 240;
  --z: 7, 7, 8;
  --11: 240, 240, 240;
  --1e: 31, 31, 31;
  --1f: 0, 0, 0;
  --13: 31, 31, 31;
  --15: 31, 31, 31;
  --17: 31, 31, 31;
  --19: 176, 176, 176;
  --1g: 5, 5, 6;
  --1h: 237, 237, 237;
  --1i: 119, 168, 249;
  --1j: 252, 252, 252;
  --1k: 5, 5, 6;
  --1l: 237, 237, 237;
  --1m: 119, 168, 249;
  --1n: 252, 252, 252;
  --1o: 5, 5, 6;
  --1p: 237, 237, 237;
  --1q: 119, 168, 249;
  --1r: 252, 252, 252;
  --1s: 58, 90, 196;
  --1t: 46, 72, 158;
  --1u: 62, 70, 96;
  --1v: 97, 92, 73;
  --1w: 116, 90, 47;
  --1x: 15, 88, 184;
  --1y: 128, 175, 249;
  --1z: 255, 224, 184;
  --20: 28, 95, 53;
  --21: 138, 40, 40;
  --22: 134, 80, 39;
  --23: 46, 72, 158;
  --24: 228, 228, 231;
  --25: 63, 63, 70;
  --26: 24, 24, 27;
  --27: 254, 249, 195;
  --28: 255, 255, 255;
  --29: 255, 255, 255;
  --2a: 255, 255, 255;
  --2b: 255, 255, 255;
  --2c: 255, 255, 255;
  --2d: 255, 255, 255;
  --2e: 0, 0, 0;
  --2f: 0, 0, 0;
  --2g: 255, 255, 255;
  --2h: 255, 255, 255;
  --2i: 255, 255, 255;
  --2j: 255, 255, 255;
```

**Comment by navanshu** [comment]
Could you please share a minimal code example on CodeSandbox? I'd like to verify if the output is correct. Also, when it comes to variables, it's important that each variable maintains its unique identity. If merged incorrectly, it could result in undesired outcomes.

**Comment by jaswrks** [comment]
Thanks so much for taking a look. I can't do that, I'm sorry. However, I can share the underlying postcss config file and a dev build of the final CSS bundle for your review. 

- https://gist.github.com/jaswrks/1d0abfb2d09b106e1ed6397e6c35738e
- https://gist.github.com/jaswrks/5c72a972c4d5481071a4bc4565508805

Our Tailwind config file is quite large and extensive. It uses various theme configurations that end up with variables that contain duplicate values, but are too difficult to optimize away from the source. It would be awesome if we could find a way to optimize the duplicate variables away that are within any given scope, leaving the others. I realize we can't get rid of them all, but anything further to help consolidate the variables that are in fact referencing the exact same value would be amazing.

**Comment by jaswrks** [comment]
Here is a dev build of the CSS w/o variable compression, in case it helps.
- https://gist.github.com/jaswrks/15ba7efe1df1e6159ef7233ee99a3598

**Comment by navanshu** [comment]
@jaswrks Looking at your codebase I feel like it optimal 👍🏽and I don't think that the amount of variable is insane, the purpose of my plugin is to handle even thousands of variables.

Though your use case makes sense on a micro level but on a global level it doesn't, the fix is possible though,

But I cannot confirm if there is any issue with the given code can you provide me the output after updating the postcss config 

```diff
- (await import('postcss-variable-compress')).default(),
+ (await import('postcss-variable-compress/splitFiles')).default(),
```

I want to confirm if the plugin is working correctly with your codebase.
