### ISSUE TITLE
How does this plugin handle deleted variables?

### ISSUE THREAD

**Issue by TKDev7** [navanshu/postcss-variable-compress#48]
Let us say I have a variable that was hashed and saved in my build history file. I later deleted this variable in my css so it is no longer used. What happens to the one in the saved file? Is the plugin smart enough to delete it?

**Comment by navanshu** [comment]
@MrHBS Thanks for pointing this out, as of now, I have only released v3 the build history will only be available in v4.

**Comment by TKDev7** [comment]
So v4 will handle the case I mentioned?

**Comment by navanshu** [comment]
@MrHBS Yes, the readme file has mention for the correct version.

**Comment by TKDev7** [comment]
I am not asking which version has the build history api. I am aware it is in v4. I am asking if the case I mentioned will be handled as well.

**Comment by navanshu** [comment]
@MrHBS Depends upon postcss's api
